SM-TM-f3759
SkillBrain-com/tinker-bell pull request #6
Opened 2024-09-16 19:30 UTC by hutyraerik

2024-09-16 19:32 UTC, hutyraerik reviewed
👍

2024-09-17 16:02 UTC, agnesKrpp approved these changes

2024-09-17 16:20 UTC, crissandu commented on src/test/java/ErikH/pageObject/AlertPageObject.java
> +
Please close main class and change the classes below NOT to be static

2024-09-17 16:21 UTC, crissandu requested changes
Please read comments

2024-09-17 17:13 UTC, crissandu approved these changes

2024-09-17 17:13 UTC, LaurAndy approved these changes

2024-09-17 17:13 UTC, merged